### ISSUE TITLE
Clicking in Start9 temp. settings GUI causes a crash

### ISSUE THREAD

**Issue by logonoff** [StartNine/Start9.Host#10]
os: fresh win7 VM, running start9 commit ``6df79d4`` (lastest ``messages`` build so far)
**steps to reproduce:**
* open start9
* click around in the GUI
* profit
[recording of issue](https://i.imgur.com/ueTPQcM.gif)

**Comment by Splitwirez** [comment]
Found the problem: The button you clicked last in the GIF attempts to do some DWM thumbnail stuff, but I have no idea how that stuff works, so it just crashes instead.

**Comment by Reflectronic** [comment]
this button doesn't exist anymore
