### ISSUE TITLE
Crashes when opening Modules test

### ISSUE THREAD

**Issue by TechGuyOneHundred** [StartNine/Start9.Host#18]
![image](https://user-images.githubusercontent.com/37509156/41435419-58d768ba-6fe4-11e8-93a8-e9e3e945491c.png)

Any Ideas or fixes

**Comment by Splitwirez** [comment]
How many times do I have to tell you that there's nothing ready for testing?

**Comment by reflectronic** [comment]
probably because you don't have the addin pipeline set up. i'll explain in much greater detail later what that exactly means but for now you have to sit tight until i find time to actually work on this
