### ISSUE TITLE
closing doesn't actually do anything..

### ISSUE THREAD

**Issue by logonoff** [StartNine/Start9.Host#8]
fresh windows 7 VM
steps to reproduce:
* open a precompiled build of start9 that was made using the start button thing
* try to close start9
* enjoy
[A build of Start9 not closing.](https://i.imgur.com/I5OtiCr.gif)

**Comment by Reflectronic** [comment]
I know this is fixed... somewhere. Might be in the Sticky9 codebase, might be in messages too

**Comment by Reflectronic** [comment]
This is why we need to organize the project better and get `Start9.Api` on Nuget (👀 on @Splitwirez)

**Comment by logonoff** [comment]
*waits for changes to roll down to master)

**Comment by logonoff** [comment]
.. will leave open until changes are tricked down to branch ``master``.

**Comment by Splitwirez** [comment]
All of the Start9 improvements resulting from Sticky9 are up on GitHub...I think they may have accidentally ended up in the messages branch though .-.

**Comment by Reflectronic** [comment]
uh oh spaghet

**Comment by Splitwirez** [comment]
...better than losing them to a hard drive crash or something, though, right? :P

**Comment by Reflectronic** [comment]
😛

**Comment by logonoff** [comment]
are you also aware of this issue? [the issue I was referring to](https://i.imgur.com/yvzH97B.png)

**Comment by Splitwirez** [comment]
wait...wat

**Comment by Splitwirez** [comment]
what am I looking at

**Comment by Reflectronic** [comment]
fixed
